apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: step-4-storage
  namespace: kommander-flux
spec:
  dependsOn:
    - name: step-3b-security-constraints
  interval: 10s
  path: ./clusters/demo/step-4-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: cncf-webinar-demo
  wait: true
  timeout: 10s
